package com.yryz.quanhu.behavior.gift.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @author wangheng
 * This class was generated by MyBatis Generator.
 * @table qh_gift_info
*/
public class GiftInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
    * 主键
    */
    private Long id;

    /**
    * 唯一编码
    */
    private Long kid;

    /**
    * 礼物名称
    */
    private String giftName;

    /**
    * 礼物图片
    */
    private String giftImage;

    /**
    * 礼物金额
    */
    private Long giftPrice;

    /**
    * 礼物价值(分费)
    */
    private Long giftValue;

    /**
    * 创建时间
    */
    private Date createDate;

    /**
    * 最后更新时间
    */
    private Date lastUpdateDate;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getKid() {
        return kid;
    }

    public void setKid(Long kid) {
        this.kid = kid;
    }

    public String getGiftName() {
        return giftName;
    }

    public void setGiftName(String giftName) {
        this.giftName = giftName;
    }

    public String getGiftImage() {
        return giftImage;
    }

    public void setGiftImage(String giftImage) {
        this.giftImage = giftImage;
    }

    public Long getGiftPrice() {
        return giftPrice;
    }

    public void setGiftPrice(Long giftPrice) {
        this.giftPrice = giftPrice;
    }

    public Long getGiftValue() {
        return giftValue;
    }

    public void setGiftValue(Long giftValue) {
        this.giftValue = giftValue;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", kid=").append(kid);
        sb.append(", giftName=").append(giftName);
        sb.append(", giftImage=").append(giftImage);
        sb.append(", giftPrice=").append(giftPrice);
        sb.append(", giftValue=").append(giftValue);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append("]");
        return sb.toString();
    }
}