package com.yryz.quanhu.behavior.reward.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @author wangheng
 * This class was generated by MyBatis Generator.
 * @table qh_reward_count
*/
public class RewardCount implements Serializable{
    private static final long serialVersionUID = 1L;

    /**
    * 主键ID
    */
    private Long id;

    /**
    * 目标ID
    */
    private Long targetId;

    /**
    * 目标类型（10：用户；11：资源）
    */
    private Byte targetType;

    /**
    * 我打赏总数
    */
    private Integer totalRewardCount;

    /**
    * 我打赏总金额
    */
    private Long totalRewardAmount;

    /**
    * 被打赏的总数
    */
    private Integer totalRewardedCount;

    /**
    * 被打赏的总金额
    */
    private Long totalRewardedAmount;

    /**
    * 创建时间
    */
    private Date createDate;

    /**
    * 最后更新时间
    */
    private Date lastUpdateDate;

    /**
    * 版本号
    */
    private Integer revision;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public Byte getTargetType() {
        return targetType;
    }

    public void setTargetType(Byte targetType) {
        this.targetType = targetType;
    }

    public Integer getTotalRewardCount() {
        return totalRewardCount;
    }

    public void setTotalRewardCount(Integer totalRewardCount) {
        this.totalRewardCount = totalRewardCount;
    }

    public Long getTotalRewardAmount() {
        return totalRewardAmount;
    }

    public void setTotalRewardAmount(Long totalRewardAmount) {
        this.totalRewardAmount = totalRewardAmount;
    }

    public Integer getTotalRewardedCount() {
        return totalRewardedCount;
    }

    public void setTotalRewardedCount(Integer totalRewardedCount) {
        this.totalRewardedCount = totalRewardedCount;
    }

    public Long getTotalRewardedAmount() {
        return totalRewardedAmount;
    }

    public void setTotalRewardedAmount(Long totalRewardedAmount) {
        this.totalRewardedAmount = totalRewardedAmount;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public Integer getRevision() {
        return revision;
    }

    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", targetId=").append(targetId);
        sb.append(", targetType=").append(targetType);
        sb.append(", totalRewardCount=").append(totalRewardCount);
        sb.append(", totalRewardAmount=").append(totalRewardAmount);
        sb.append(", totalRewardedCount=").append(totalRewardedCount);
        sb.append(", totalRewardedAmount=").append(totalRewardedAmount);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", revision=").append(revision);
        sb.append("]");
        return sb.toString();
    }
}