package com.yryz.quanhu.resource.release.config.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReleaseConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qh_release_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qh_release_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qh_release_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    public ReleaseConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * @table qh_release_config
    */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClassifyIdIsNull() {
            addCriterion("classify_id is null");
            return (Criteria) this;
        }

        public Criteria andClassifyIdIsNotNull() {
            addCriterion("classify_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyIdEqualTo(Long value) {
            addCriterion("classify_id =", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdNotEqualTo(Long value) {
            addCriterion("classify_id <>", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdGreaterThan(Long value) {
            addCriterion("classify_id >", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("classify_id >=", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdLessThan(Long value) {
            addCriterion("classify_id <", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdLessThanOrEqualTo(Long value) {
            addCriterion("classify_id <=", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdIn(List<Long> values) {
            addCriterion("classify_id in", values, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdNotIn(List<Long> values) {
            addCriterion("classify_id not in", values, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdBetween(Long value1, Long value2) {
            addCriterion("classify_id between", value1, value2, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdNotBetween(Long value1, Long value2) {
            addCriterion("classify_id not between", value1, value2, "classifyId");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyIsNull() {
            addCriterion("property_key is null");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyIsNotNull() {
            addCriterion("property_key is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyEqualTo(String value) {
            addCriterion("property_key =", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyNotEqualTo(String value) {
            addCriterion("property_key <>", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyGreaterThan(String value) {
            addCriterion("property_key >", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyGreaterThanOrEqualTo(String value) {
            addCriterion("property_key >=", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyLessThan(String value) {
            addCriterion("property_key <", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyLessThanOrEqualTo(String value) {
            addCriterion("property_key <=", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyLike(String value) {
            addCriterion("property_key like", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyNotLike(String value) {
            addCriterion("property_key not like", value, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyIn(List<String> values) {
            addCriterion("property_key in", values, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyNotIn(List<String> values) {
            addCriterion("property_key not in", values, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyBetween(String value1, String value2) {
            addCriterion("property_key between", value1, value2, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyKeyNotBetween(String value1, String value2) {
            addCriterion("property_key not between", value1, value2, "propertyKey");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasIsNull() {
            addCriterion("property_alias is null");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasIsNotNull() {
            addCriterion("property_alias is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasEqualTo(String value) {
            addCriterion("property_alias =", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasNotEqualTo(String value) {
            addCriterion("property_alias <>", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasGreaterThan(String value) {
            addCriterion("property_alias >", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasGreaterThanOrEqualTo(String value) {
            addCriterion("property_alias >=", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasLessThan(String value) {
            addCriterion("property_alias <", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasLessThanOrEqualTo(String value) {
            addCriterion("property_alias <=", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasLike(String value) {
            addCriterion("property_alias like", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasNotLike(String value) {
            addCriterion("property_alias not like", value, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasIn(List<String> values) {
            addCriterion("property_alias in", values, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasNotIn(List<String> values) {
            addCriterion("property_alias not in", values, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasBetween(String value1, String value2) {
            addCriterion("property_alias between", value1, value2, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andPropertyAliasNotBetween(String value1, String value2) {
            addCriterion("property_alias not between", value1, value2, "propertyAlias");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Byte value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Byte value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Byte value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Byte value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Byte value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Byte value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Byte> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Byte> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Byte value1, Byte value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Byte value1, Byte value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andRequiredIsNull() {
            addCriterion("required is null");
            return (Criteria) this;
        }

        public Criteria andRequiredIsNotNull() {
            addCriterion("required is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredEqualTo(Byte value) {
            addCriterion("required =", value, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredNotEqualTo(Byte value) {
            addCriterion("required <>", value, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredGreaterThan(Byte value) {
            addCriterion("required >", value, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredGreaterThanOrEqualTo(Byte value) {
            addCriterion("required >=", value, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredLessThan(Byte value) {
            addCriterion("required <", value, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredLessThanOrEqualTo(Byte value) {
            addCriterion("required <=", value, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredIn(List<Byte> values) {
            addCriterion("required in", values, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredNotIn(List<Byte> values) {
            addCriterion("required not in", values, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredBetween(Byte value1, Byte value2) {
            addCriterion("required between", value1, value2, "required");
            return (Criteria) this;
        }

        public Criteria andRequiredNotBetween(Byte value1, Byte value2) {
            addCriterion("required not between", value1, value2, "required");
            return (Criteria) this;
        }

        public Criteria andLowerLimitIsNull() {
            addCriterion("lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andLowerLimitIsNotNull() {
            addCriterion("lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andLowerLimitEqualTo(Integer value) {
            addCriterion("lower_limit =", value, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitNotEqualTo(Integer value) {
            addCriterion("lower_limit <>", value, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitGreaterThan(Integer value) {
            addCriterion("lower_limit >", value, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("lower_limit >=", value, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitLessThan(Integer value) {
            addCriterion("lower_limit <", value, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitLessThanOrEqualTo(Integer value) {
            addCriterion("lower_limit <=", value, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitIn(List<Integer> values) {
            addCriterion("lower_limit in", values, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitNotIn(List<Integer> values) {
            addCriterion("lower_limit not in", values, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitBetween(Integer value1, Integer value2) {
            addCriterion("lower_limit between", value1, value2, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andLowerLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("lower_limit not between", value1, value2, "lowerLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitIsNull() {
            addCriterion("upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andUpperLimitIsNotNull() {
            addCriterion("upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andUpperLimitEqualTo(Integer value) {
            addCriterion("upper_limit =", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitNotEqualTo(Integer value) {
            addCriterion("upper_limit <>", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitGreaterThan(Integer value) {
            addCriterion("upper_limit >", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("upper_limit >=", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitLessThan(Integer value) {
            addCriterion("upper_limit <", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitLessThanOrEqualTo(Integer value) {
            addCriterion("upper_limit <=", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitIn(List<Integer> values) {
            addCriterion("upper_limit in", values, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitNotIn(List<Integer> values) {
            addCriterion("upper_limit not in", values, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitBetween(Integer value1, Integer value2) {
            addCriterion("upper_limit between", value1, value2, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("upper_limit not between", value1, value2, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andInputPromptIsNull() {
            addCriterion("input_prompt is null");
            return (Criteria) this;
        }

        public Criteria andInputPromptIsNotNull() {
            addCriterion("input_prompt is not null");
            return (Criteria) this;
        }

        public Criteria andInputPromptEqualTo(String value) {
            addCriterion("input_prompt =", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptNotEqualTo(String value) {
            addCriterion("input_prompt <>", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptGreaterThan(String value) {
            addCriterion("input_prompt >", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptGreaterThanOrEqualTo(String value) {
            addCriterion("input_prompt >=", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptLessThan(String value) {
            addCriterion("input_prompt <", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptLessThanOrEqualTo(String value) {
            addCriterion("input_prompt <=", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptLike(String value) {
            addCriterion("input_prompt like", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptNotLike(String value) {
            addCriterion("input_prompt not like", value, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptIn(List<String> values) {
            addCriterion("input_prompt in", values, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptNotIn(List<String> values) {
            addCriterion("input_prompt not in", values, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptBetween(String value1, String value2) {
            addCriterion("input_prompt between", value1, value2, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andInputPromptNotBetween(String value1, String value2) {
            addCriterion("input_prompt not between", value1, value2, "inputPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptIsNull() {
            addCriterion("error_prompt is null");
            return (Criteria) this;
        }

        public Criteria andErrorPromptIsNotNull() {
            addCriterion("error_prompt is not null");
            return (Criteria) this;
        }

        public Criteria andErrorPromptEqualTo(String value) {
            addCriterion("error_prompt =", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptNotEqualTo(String value) {
            addCriterion("error_prompt <>", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptGreaterThan(String value) {
            addCriterion("error_prompt >", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptGreaterThanOrEqualTo(String value) {
            addCriterion("error_prompt >=", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptLessThan(String value) {
            addCriterion("error_prompt <", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptLessThanOrEqualTo(String value) {
            addCriterion("error_prompt <=", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptLike(String value) {
            addCriterion("error_prompt like", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptNotLike(String value) {
            addCriterion("error_prompt not like", value, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptIn(List<String> values) {
            addCriterion("error_prompt in", values, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptNotIn(List<String> values) {
            addCriterion("error_prompt not in", values, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptBetween(String value1, String value2) {
            addCriterion("error_prompt between", value1, value2, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andErrorPromptNotBetween(String value1, String value2) {
            addCriterion("error_prompt not between", value1, value2, "errorPrompt");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpIsNull() {
            addCriterion("check_regExp is null");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpIsNotNull() {
            addCriterion("check_regExp is not null");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpEqualTo(String value) {
            addCriterion("check_regExp =", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpNotEqualTo(String value) {
            addCriterion("check_regExp <>", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpGreaterThan(String value) {
            addCriterion("check_regExp >", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpGreaterThanOrEqualTo(String value) {
            addCriterion("check_regExp >=", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpLessThan(String value) {
            addCriterion("check_regExp <", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpLessThanOrEqualTo(String value) {
            addCriterion("check_regExp <=", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpLike(String value) {
            addCriterion("check_regExp like", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpNotLike(String value) {
            addCriterion("check_regExp not like", value, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpIn(List<String> values) {
            addCriterion("check_regExp in", values, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpNotIn(List<String> values) {
            addCriterion("check_regExp not in", values, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpBetween(String value1, String value2) {
            addCriterion("check_regExp between", value1, value2, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCheckRegexpNotBetween(String value1, String value2) {
            addCriterion("check_regExp not between", value1, value2, "checkRegexp");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("last_update_date is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("last_update_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("last_update_date =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("last_update_date <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("last_update_date >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_date >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("last_update_date <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("last_update_date <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("last_update_date in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("last_update_date not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("last_update_date between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("last_update_date not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdIsNull() {
            addCriterion("last_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdIsNotNull() {
            addCriterion("last_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdEqualTo(Long value) {
            addCriterion("last_update_user_id =", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotEqualTo(Long value) {
            addCriterion("last_update_user_id <>", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdGreaterThan(Long value) {
            addCriterion("last_update_user_id >", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("last_update_user_id >=", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdLessThan(Long value) {
            addCriterion("last_update_user_id <", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("last_update_user_id <=", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdIn(List<Long> values) {
            addCriterion("last_update_user_id in", values, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotIn(List<Long> values) {
            addCriterion("last_update_user_id not in", values, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("last_update_user_id between", value1, value2, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("last_update_user_id not between", value1, value2, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andRevisionIsNull() {
            addCriterion("revision is null");
            return (Criteria) this;
        }

        public Criteria andRevisionIsNotNull() {
            addCriterion("revision is not null");
            return (Criteria) this;
        }

        public Criteria andRevisionEqualTo(Integer value) {
            addCriterion("revision =", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionNotEqualTo(Integer value) {
            addCriterion("revision <>", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionGreaterThan(Integer value) {
            addCriterion("revision >", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionGreaterThanOrEqualTo(Integer value) {
            addCriterion("revision >=", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionLessThan(Integer value) {
            addCriterion("revision <", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionLessThanOrEqualTo(Integer value) {
            addCriterion("revision <=", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionIn(List<Integer> values) {
            addCriterion("revision in", values, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionNotIn(List<Integer> values) {
            addCriterion("revision not in", values, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionBetween(Integer value1, Integer value2) {
            addCriterion("revision between", value1, value2, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionNotBetween(Integer value1, Integer value2) {
            addCriterion("revision not between", value1, value2, "revision");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * @table qh_release_config
    */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * @table qh_release_config
    */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}